@hostname = http://localhost
@port = 8080
@suffix = /api/v1
@url = {{hostname}}:{{port}}{{suffix}}
@contentType = application/json

### Login
POST {{url}}/auth/login
Content-Type: {{contentType}}

{
  "email": "foo@bar.com",
  "password": "password"
}

### Me
GET {{url}}/auth/me
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

### Refresh Token
POST {{url}}/auth/refresh-token
Content-Type: {{contentType}}

{
  "token": "{{refreshToken}}"
}
### Register
POST {{url}}/auth/register
Content-Type: {{contentType}}

{
  "email": "foo@bar.com",
  "password": "password"
}