version: "3.5"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - hey-taxi-network

volumes:
  mongo-volume:

networks:
  hey-taxi-network:
    external:
      name: hey-taxi-network
    driver: bridge