//go:build swagger
// +build swagger

package swagger

import (
	"github.com/labstack/echo/v4"
	_ "github.com/orkungursel/hey-taxi-identity-api/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/orkungursel/hey-taxi-identity-api/pkg/server"
	echoSwagger "github.com/swaggo/echo-swagger"
)

type SwaggerApi struct {
	*server.Server
}

func Api(s *server.Server) *SwaggerApi {
	api := &SwaggerApi{
		Server: s,
	}

	if err := s.AddApiToRoot("/swagger/*", api); err != nil {
		panic(err)
	}

	return api
}

func (s *SwaggerApi) RegisterRoutes(group *echo.Group) {
	group.GET("", echoSwagger.WrapHandler)
}
