//go:build dev

package swagger

import (
	"github.com/labstack/echo/v4"
	_ "github.com/orkungursel/hey-taxi-identity-api/docs" // docs is generated by Swag CLI
	"github.com/orkungursel/hey-taxi-identity-api/pkg/server"
	echoSwagger "github.com/swaggo/echo-swagger"
)

type SwaggerApi struct {
	*server.Server
}

func Api(s *server.Server) {
	api := &SwaggerApi{
		Server: s,
	}

	if err := s.RegisterHttpApiAsRoot("/swagger/*", api); err != nil {
		panic(err)
	}

	s.Logger().Info("swagger is enabled")
}

func (s *SwaggerApi) RegisterRoutes(group *echo.Group) {
	group.GET("", echoSwagger.WrapHandler)
}
