// Code generated by MockGen. DO NOT EDIT.
// Source: password_service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIPasswordService is a mock of IPasswordService interface.
type MockIPasswordService struct {
	ctrl     *gomock.Controller
	recorder *MockIPasswordServiceMockRecorder
}

// MockIPasswordServiceMockRecorder is the mock recorder for MockIPasswordService.
type MockIPasswordServiceMockRecorder struct {
	mock *MockIPasswordService
}

// NewMockIPasswordService creates a new mock instance.
func NewMockIPasswordService(ctrl *gomock.Controller) *MockIPasswordService {
	mock := &MockIPasswordService{ctrl: ctrl}
	mock.recorder = &MockIPasswordServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPasswordService) EXPECT() *MockIPasswordServiceMockRecorder {
	return m.recorder
}

// Compare mocks base method.
func (m *MockIPasswordService) Compare(ctx context.Context, hashedPassword, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", ctx, hashedPassword, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compare indicates an expected call of Compare.
func (mr *MockIPasswordServiceMockRecorder) Compare(ctx, hashedPassword, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*MockIPasswordService)(nil).Compare), ctx, hashedPassword, password)
}

// Hash mocks base method.
func (m *MockIPasswordService) Hash(ctx context.Context, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", ctx, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockIPasswordServiceMockRecorder) Hash(ctx, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockIPasswordService)(nil).Hash), ctx, password)
}
